1. Construct an array from the list: [1,2,3]

In [2]:
import numpy as np
arr = np.arr([1, 2, 3])
print(arr)

[1 2 3]


2. Cast it into floats

In [3]:
arr = arr.astype(float)
print(arr)

[1. 2. 3.]


3. Create an array of int ranging from 0-10 

In [5]:
arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


4. Create an array containing 7 evenly spaced numbers between 0 and 23

In [7]:
arr = np.linspace(0, 23, 7)
print(arr)

[ 0.          3.83333333  7.66666667 11.5        15.33333333 19.16666667
 23.        ]


5. Create an array with shape (2,5,1,5,2,1) containing only the number 5

In [8]:
arr = np.full((2,5,1,5,2,1), 5)
print(arr)

[[[[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]]




 [[[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]]]



  [[[[5]
     [5]]

    [[5]
     [5]]

    [[5]
     [5]]

  

6. Eliminate all length-1 dimensions. See the function squeeze.

In [24]:
arr = np.full((2,5,1,5,2,1), 5)
arr = np.squeeze(arr)
print(arr)

[[[[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]]


 [[[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]

  [[5 5]
   [5 5]
   [5 5]
   [5 5]
   [5 5]]]]


7. Reshape the resulting array from shape (2,5,3,2) to only 2D

In [11]:
arr = arr.reshape(-1, np.prod(arr.shape[1:]))
print(arr)

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


8. Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.

In [15]:
import numpy as np
arr = np.random.normal(21, 4.5, size=(3,3,12,3))
print("array : ",arr)
mean = np.mean(arr)
print("mean : ",mean)
std = np.std(arr)
print("std : ",std)
var = np.var(arr)
print("var : ",var)
max_val = np.max(arr)
print("max_val : ",max_val)
min_val = np.min(arr)
print("min_val : ",min_val)

array :  [[[[24.52309506 19.87147989 24.36387456]
   [14.87448306 27.51471562 17.89094759]
   [24.43387782 23.35749201 20.08240905]
   [22.42485101 17.87406005 23.83047219]
   [14.98105315 13.92752624 24.67523063]
   [24.10102379 13.90414544 19.46107515]
   [26.2320895  22.46632848 24.83333542]
   [24.68528118 17.52766402 11.99689637]
   [17.81049418 21.99189857 20.2479392 ]
   [21.35441955 24.53577402 18.26392182]
   [21.83364385 21.79298259 19.18472713]
   [27.22439439 25.66072956 22.21119   ]]

  [[27.18647787 14.11261228 22.40434919]
   [25.40305526 21.97592226 21.95507964]
   [23.59215867 17.55008584 28.64928739]
   [14.62381176 12.29562045 20.38207441]
   [23.1645681  23.74020272 22.52734272]
   [19.54451051 24.58880405 26.98337203]
   [19.1232827  24.5209453  17.79457266]
   [16.75114254 24.32394149 14.46973232]
   [14.9512295  20.81072022 20.27856038]
   [21.84195377 19.75375574 18.09353627]
   [22.0234482  20.32194647 18.69523141]
   [21.06309595 18.20842472 23.32144972]]

  [

9. Do the same but not on all elements but only on the 2nd dimension. 

In [16]:
mean = np.mean(arr, axis=1)
print("mean : ",mean)
std = np.std(arr, axis=1)
print("std : ",std)
var = np.var(arr, axis=1)
print("var : ",var)
max_val = np.max(arr, axis=1)
print("max_val : ",max_val)
min_val = np.min(arr, axis=1)
print("min_val : ",min_val)

mean :  [[[24.92999276 18.61694751 20.12897363]
  [23.07761797 25.25779164 18.97623917]
  [23.79354505 22.1181495  23.33921548]
  [18.58144128 14.61285442 19.07683965]
  [19.92549765 18.110361   23.67149331]
  [20.62358708 20.93731484 20.28717727]
  [21.261807   22.96262602 20.7320431 ]
  [20.79109799 19.15263183 15.25663278]
  [15.06203356 21.06774386 22.29791658]
  [20.3362959  22.08894191 19.01314543]
  [24.18744775 19.38042442 22.23329751]
  [23.94243381 23.74336403 22.60232727]]

 [[18.12750024 22.64662444 11.93522458]
  [20.73236312 21.49246423 21.06485562]
  [20.5391823  19.85850452 20.85613866]
  [17.81583467 23.21676299 22.27978748]
  [21.36118858 18.2092759  22.79035767]
  [25.26492254 18.73015656 21.52908754]
  [20.93414181 22.57849317 27.15258332]
  [25.4272924  19.61997627 22.42521779]
  [21.57483923 17.79106946 18.46850092]
  [16.2388834  25.49851805 20.61965048]
  [20.16030924 22.00614536 23.1504766 ]
  [17.45555237 22.63639513 23.276289  ]]

 [[19.00025946 24.99242395 1

10. Transform the array such that it is only 1d. See the function Flatten or ravel

In [17]:
arr = arr.ravel()
print(arr)

[24.52309506 19.87147989 24.36387456 14.87448306 27.51471562 17.89094759
 24.43387782 23.35749201 20.08240905 22.42485101 17.87406005 23.83047219
 14.98105315 13.92752624 24.67523063 24.10102379 13.90414544 19.46107515
 26.2320895  22.46632848 24.83333542 24.68528118 17.52766402 11.99689637
 17.81049418 21.99189857 20.2479392  21.35441955 24.53577402 18.26392182
 21.83364385 21.79298259 19.18472713 27.22439439 25.66072956 22.21119
 27.18647787 14.11261228 22.40434919 25.40305526 21.97592226 21.95507964
 23.59215867 17.55008584 28.64928739 14.62381176 12.29562045 20.38207441
 23.1645681  23.74020272 22.52734272 19.54451051 24.58880405 26.98337203
 19.1232827  24.5209453  17.79457266 16.75114254 24.32394149 14.46973232
 14.9512295  20.81072022 20.27856038 21.84195377 19.75375574 18.09353627
 22.0234482  20.32194647 18.69523141 21.06309595 18.20842472 23.32144972
 23.08040534 21.86675035 13.61869713 28.9553156  26.28273702 17.08269029
 23.35459868 25.44687065 21.28594999 18.69566107 13.66